### ISSUE TITLE
Unable to do bower install for jquery-ui version 1.13.1 using bower.json

### ISSUE THREAD

**Issue by manpuriasudip** [jquery/jquery-ui#2068]
Doing a bower install on the below bower.json fails with the error - 

sample bower,json - 
```json
{
    "dependencies": {
        "jquery": "^3.5",
        "lodash": "^4",
        "jquery-ui": "^1.13.1",

    },
    
  "resolutions": {
    "jquery": "3.5.1"
  }
}
```
Error - 
```
Message:
    No version found that was able to satisfy 1.13.1
Details:
    code: ENORESTARGET
    details: Available versions: 1.10.0, 1.10.1, 1.10.2, 1.10.3, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.11.4, 1.12.0, 1.12.1, 1.8.23, 1.9.0, 1.9.1, 1.9.2
    data: [object Object]
    domainEmitter: [object Object]
    domainThrown: false
```

<sub>EDIT by @mgol: Wrapped code in code blocks</sub>
