### ISSUE TITLE
IE filter property has incorrect value for the widget-overlay v1.13

### ISSUE THREAD

**Issue by Diazole** [jquery/jquery-ui#2190]
IE filter property values were updated to strings by https://github.com/jquery/jquery-ui/pull/1939.

However, the filter value for the widget-overlay hasn't been updated in the output CSS file (https://github.com/jquery/jquery-ui/blob/1.13.2/dist/themes/base/theme.css#L441).

All of the other filters have been updated to strings in the output file, so I'm not sure why this one wasn't?

**Comment by Diazole** [comment]
The v1.13.2 stable release has:

```css
/* Overlays */
.ui-widget-overlay {
	background: #aaaaaa;
	opacity: .003;
	-ms-filter: Alpha(Opacity=.3); /* support: IE8 */
}
```

But the base theme for v1.13.2 has:

```css
/* Overlays */
.ui-widget-overlay {
	background: #aaaaaa/*{bgColorOverlay}*/ /*{bgImgUrlOverlay}*/ /*{bgOverlayXPos}*/ /*{bgOverlayYPos}*/ /*{bgOverlayRepeat}*/;
	opacity: .3/*{opacityOverlay}*/;
	-ms-filter: "alpha(opacity=30)"/*{opacityFilterOverlay}*/; /* support: IE8 */
}
```

So not only is the filter different, the opacity is too?
