### ISSUE TITLE
Draggable should compensate for transform: scale on parent element

### ISSUE THREAD

**Issue by Niels-NTG** [jquery/jquery-ui#2261]
Hello,

For our webapp has a feature which allows the user to "present" their content for a big screen. For this we apply this CSS

```scss
.container {
    --scale-factor: 1;

    @media (min-width: 1440px) {
        --scale-factor: 1.1;
    }

    @media (min-width: 1920px) {
        --scale-factor: 1.4;
    }

    @media (min-width: 2560px) {
        --scale-factor: 1.9;
    }

    @media (min-width: 3840px) {
        --scale-factor: 2.1;
    }

   .content {
       transform: scale(var(--scale-factor));
   }
}
```

Any instance of draggable, sortable and droppable that is a direct or indirect child of `.content` doesn't look quite right if `--scale-factor` is not equal to `1`. When dropping items in the sortable it drops the dragged item at the expected position, but the position of the "helper" element does not stay attached to the cursor's position. See images below:

The draggable. Items have `containment` on the direct parent element and I use `helper: 'original'`.
![Scherm­afbeelding 2024-06-06 om 14 52 21 (2)](https://github.com/jquery/jquery-ui/assets/6061595/7f6825ff-bd6d-4f88-97ea-c7c7619f58c0)

When starting to drag the first item, the `top` attribute of the helper is multiplied by the scaling of a parent element, resulting in the helper item (in red) being offset from my cursor.
![Scherm­afbeelding 2024-06-06 om 14 50 30 (2)](https://github.com/jquery/jquery-ui/assets/6061595/1ac52436-3e65-4ca1-ad1e-e8c1e09e1dc9)
The distance from the cursor and the helper element gets bigger the further down the list I go.
![Scherm­afbeelding 2024-06-06 om 14 57 00 (2)](https://github.com/jquery/jquery-ui/assets/6061595/b2cb2230-e632-411b-b60d-af9ced8ec30d)

The discrepancy between jQuery UI being able to figure out the correct position of the drop target but not the position of the helper suggests to me there is a bug in how the translation of the helper is calculated. Maybe this can be fixed or an option can be added to the API for `scale`, so jQueryUI can adjust the positioning of the helper accordingly.
